<template>
  <div class="entry-container">
    <download-csv
    style="margin-top: 10px"
    :data="jsonData"
    name="Data.csv">
    <v-btn color=" #F6E1E1" class="download"
    style="background: #FFFFFF ; color: #770000 "
    >Download CSV
      <v-icon>mdi-download</v-icon>
    </v-btn>
  </download-csv>
  </div>
</template>

<script>
import JsonCSV from 'vue-json-csv'
export default {
  name: 'Json',
  components: {'downloadCsv': JsonCSV},
  data(){
    return{
      jsonData:[{
       name: 'Ezra',
      'Site name': 'Manenberg',
      'Site type': 'Mount View High',
      'Sub district': 'Cape Flats',
      'Date': '13 January 2021',
      'Counsellor name': 'Anwar',
      'Time in': '11h00',
      'Gender': 'Male',
      'Birthdate': '10 May 1994',
      'Age at intake':'18',
      'Grade':'12',
      'Race':'Coloured',
      'Mobile': '0788414676',
      'Consent to sms': '0743805364',
      'Home phone number': '021 511 4532',
      'Client community': 'Manenberg',
      'Client name and surname':'Erza Settley',
      'First time doing an Hiv test':'Yes' ,
      'First time doing with Life Choices': 'Yes',
      'How many times tested': '10',
      'Last Hiv test': 'last year September',
      'Last test result': 'Negative',
      'TB screening result': 'None',
      'Scheduled follow up test': 'None',
      'Has client ever had sex': 'Yes',
      'Last had unprotected sex': '2017',
      'Blood contact': 'None',
      'STI screening result': 'None',
      'Time out': '16h00',
      'Last name': 'Settley',
      'Salesforce Client Code': '1234567',
      'Receive test results': 'Yes',
      'Reason for no test result': 'None',
      'Hiv test result': 'Negative',
      'Maintenance plan': 'None',
      'Negative client risk 1': 'None',
      'Negative client risk 2': 'None',
      'Negative client risk 3': 'None',
      'Negative client risk 1 stage': 'None',
      'Negative client risk 2 stage': 'None',
      'Negative client risk 3 stage': 'None',
      'Negative client risk 1 plan': 'None',
      'Negative client risk 2 plan': 'None',
      'Negative client risk 3 plan': 'None',
      'Pos client step 1': 'None',
      'Pos client step 2': 'None',
      'Pos client step 3': 'None',
      'Pos client step 4': 'None',
      'Pos client step 1 action plan': 'None',
      'Pos client step 2 action plan': 'None',
      'Pos client step 3 action plan': 'None',
      'Pos client risk 1': 'None',
      'Pos client risk 2': 'None',
      'Pos client risk 3': 'None',
      'Pos client risk 1 stage': 'None',
      'Pos client risk 2 stage': 'None',
      'Pos client risk 3 stage': 'None',
      'Pos client risk 1 plan': 'None',
      'Pos client risk 2 plan': 'None',
      'Pos client risk 3 plan': 'None',
      'Referral': 'None',
      'Referral Point': 'None',
      'Why was the client referred': 'None',
      'End of window period': 'None',
      'Follow up required': 'None',
      'Reason for follow up': 'None',
      'Follow up date': 'None',
  },
  {
      name: 'Justin',
      'Site name': 'Delft',
      'Site type': 'Roosendal',
      'Sub district': 'North Suburbs',
      'Date': '11 January 2021',
      'Counsellor name': 'Anwar',
      'Time in': '14h15',
      'Gender': 'Male',
      'Birthdate': '30 June 1999',
      'Age at intake':'17',
      'Grade':'10',
      'Race':'White',
      'Mobile': '0848780433',
      'Consent to sms': '0748030407',
      'Home phone number': '021 511 0102',
      'Client community': 'Delft',
      'Client name and surname':'Justin Cupido',
      'First time doing an Hiv test':'Yes' ,
      'First time doing with Life Choices': 'Yes',
      'How many times tested': '10',
      'Last Hiv test': 'last year September',
      'Last test result': 'Negative',
      'TB screening result': 'None',
      'Scheduled follow up test': 'None',
      'Has client ever had sex': 'Yes',
      'Last had unprotected sex': 'Havent yet',
      'Blood contact': 'None',
      'STI screening result': 'None',
      'Time out': '16h00',
      'Last name': 'Cupido',
      'Salesforce Client Code': '1234567',
      'Receive test results': 'Yes',
      'Reason for no test result': 'None',
      'Hiv test result': 'Negative',
      'Maintenance plan': 'None',
      'Negative client risk 1': 'None',
      'Negative client risk 2': 'None',
      'Negative client risk 3': 'None',
      'Negative client risk 1 stage': 'None',
      'Negative client risk 2 stage': 'None',
      'Negative client risk 3 stage': 'None',
      'Negative client risk 1 plan': 'None',
      'Negative client risk 2 plan': 'None',
      'Negative client risk 3 plan': 'None',
      'Pos client step 1': 'None',
      'Pos client step 2': 'None',
      'Pos client step 3': 'None',
      'Pos client step 4': 'None',
      'Pos client step 1 action plan': 'None',
      'Pos client step 2 action plan': 'None',
      'Pos client step 3 action plan': 'None',
      'Pos client risk 1': 'None',
      'Pos client risk 2': 'None',
      'Pos client risk 3': 'None',
      'Pos client risk 1 stage': 'None',
      'Pos client risk 2 stage': 'None',
      'Pos client risk 3 stage': 'None',
      'Pos client risk 1 plan': 'None',
      'Pos client risk 2 plan': 'None',
      'Pos client risk 3 plan': 'None',
      'Referral': 'None',
      'Referral Point': 'None',
      'Why was the client referred': 'None',
      'End of window period': 'None',
      'Follow up required': 'None',
      'Reason for follow up': 'None',
      'Follow up date': 'None',
  },
  {
      name: 'Skylar',
      'Site name': 'Brakenfell',
      'Site type': 'Brakenfell High',
      'Sub district': 'Northern Suburbs',
      'Date': '10 January 2021',
      'Counsellor name': 'Anwar',
      'Time in': '15h00',
      'Gender': 'Female',
      'Birthdate': '6 September 1997',
      'Age at intake':'16',
      'Grade':'11',
      'Race':'Coloured',
      'Mobile': '0786093748',
      'Consent to sms': '0738293672',
      'Home phone number': '021 502 6464',
      'Client community': 'Brakenfell',
      'Client name and surname':'Skylar Williams',
      'First time doing an Hiv test':'Yes' ,
      'First time doing with Life Choices': 'Yes',
      'How many times tested': '10',
      'Last Hiv test': 'last year November',
      'Last test result': 'Negative',
      'TB screening result': 'None',
      'Scheduled follow up test': 'None',
      'Has client ever had sex': 'Yes',
      'Last had unprotected sex': '2019',
      'Blood contact': 'None',
      'STI screening result': 'None',
      'Time out': '16h00',
      'Last name': 'Williams',
      'Salesforce Client Code': '1234567',
      'Receive test results': 'Yes',
      'Reason for no test result': 'None',
      'Hiv test result': 'Negative',
      'Maintenance plan': 'None',
      'Negative client risk 1': 'None',
      'Negative client risk 2': 'None',
      'Negative client risk 3': 'None',
      'Negative client risk 1 stage': 'None',
      'Negative client risk 2 stage': 'None',
      'Negative client risk 3 stage': 'None',
      'Negative client risk 1 plan': 'None',
      'Negative client risk 2 plan': 'None',
      'Negative client risk 3 plan': 'None',
      'Pos client step 1': 'None',
      'Pos client step 2': 'None',
      'Pos client step 3': 'None',
      'Pos client step 4': 'None',
      'Pos client step 1 action plan': 'None',
      'Pos client step 2 action plan': 'None',
      'Pos client step 3 action plan': 'None',
      'Pos client risk 1': 'None',
      'Pos client risk 2': 'None',
      'Pos client risk 3': 'None',
      'Pos client risk 1 stage': 'None',
      'Pos client risk 2 stage': 'None',
      'Pos client risk 3 stage': 'None',
      'Pos client risk 1 plan': 'None',
      'Pos client risk 2 plan': 'None',
      'Pos client risk 3 plan': 'None',
      'Referral': 'None',
      'Referral Point': 'None',
      'Why was the client referred': 'None',
      'End of window period': 'None',
      'Follow up required': 'None',
      'Reason for follow up': 'None',
      'Follow up date': 'None',
  },
    {
        name: 'Ezra',
      'Site name': 'Manenberg',
      'Site type': 'Mount View High',
      'Sub district': 'Cape Flats',
      'Date': '13 January 2021',
      'Counsellor name': 'Anwar',
      'Time in': '11h00',
      'Gender': 'Male',
      'Birthdate': '10 May 1994',
      'Age at intake':'18',
      'Grade':'12',
      'Race':'Coloured',
      'Mobile': '0788414676',
      'Consent to sms': '0743805364',
      'Home phone number': '021 511 4532',
      'Client community': 'Manenberg',
      'Client name and surname':'Erza Settley',
      'First time doing an Hiv test':'Yes' ,
      'First time doing with Life Choices': 'Yes',
      'How many times tested': '10',
      'Last Hiv test': 'last year September',
      'Last test result': 'Negative',
      'TB screening result': 'None',
      'Scheduled follow up test': 'None',
      'Has client ever had sex': 'Yes',
      'Last had unprotected sex': '2017',
      'Blood contact': 'None',
      'STI screening result': 'None',
      'Time out': '16h00',
      'Last name': 'Settley',
      'Salesforce Client Code': '1234567',
      'Receive test results': 'Yes',
      'Reason for no test result': 'None',
      'Hiv test result': 'Negative',
      'Maintenance plan': 'None',
      'Negative client risk 1': 'None',
      'Negative client risk 2': 'None',
      'Negative client risk 3': 'None',
      'Negative client risk 1 stage': 'None',
      'Negative client risk 2 stage': 'None',
      'Negative client risk 3 stage': 'None',
      'Negative client risk 1 plan': 'None',
      'Negative client risk 2 plan': 'None',
      'Negative client risk 3 plan': 'None',
      'Pos client step 1': 'None',
      'Pos client step 2': 'None',
      'Pos client step 3': 'None',
      'Pos client step 4': 'None',
      'Pos client step 1 action plan': 'None',
      'Pos client step 2 action plan': 'None',
      'Pos client step 3 action plan': 'None',
      'Pos client risk 1': 'None',
      'Pos client risk 2': 'None',
      'Pos client risk 3': 'None',
      'Pos client risk 1 stage': 'None',
      'Pos client risk 2 stage': 'None',
      'Pos client risk 3 stage': 'None',
      'Pos client risk 1 plan': 'None',
      'Pos client risk 2 plan': 'None',
      'Pos client risk 3 plan': 'None',
      'Referral': 'None',
      'Referral Point': 'None',
      'Why was the client referred': 'None',
      'End of window period': 'None',
      'Follow up required': 'None',
      'Reason for follow up': 'None',
      'Follow up date': 'None',
  },
  {
      name: 'Justin',
      'Site name': 'Delft',
      'Site type': 'Roosendal',
      'Sub district': 'North Suburbs',
      'Date': '11 January 2021',
      'Counsellor name': 'Anwar',
      'Time in': '14h15',
      'Gender': 'Male',
      'Birthdate': '30 June 1999',
      'Age at intake':'17',
      'Grade':'10',
      'Race':'White',
      'Mobile': '0848780433',
      'Consent to sms': '0748030407',
      'Home phone number': '021 511 0102',
      'Client community': 'Delft',
      'Client name and surname':'Justin Cupido',
      'First time doing an Hiv test':'Yes' ,
      'First time doing with Life Choices': 'Yes',
      'How many times tested': '10',
      'Last Hiv test': 'last year September',
      'Last test result': 'Negative',
      'TB screening result': 'None',
      'Scheduled follow up test': 'None',
      'Has client ever had sex': 'Yes',
      'Last had unprotected sex': 'Havent yet',
      'Blood contact': 'None',
      'STI screening result': 'None',
      'Time out': '16h00',
      'Last name': 'Cupido',
      'Salesforce Client Code': '1234567',
      'Receive test results': 'Yes',
      'Reason for no test result': 'None',
      'Hiv test result': 'Negative',
      'Maintenance plan': 'None',
      'Negative client risk 1': 'None',
      'Negative client risk 2': 'None',
      'Negative client risk 3': 'None',
      'Negative client risk 1 stage': 'None',
      'Negative client risk 2 stage': 'None',
      'Negative client risk 3 stage': 'None',
      'Negative client risk 1 plan': 'None',
      'Negative client risk 2 plan': 'None',
      'Negative client risk 3 plan': 'None',
      'Pos client step 1': 'None',
      'Pos client step 2': 'None',
      'Pos client step 3': 'None',
      'Pos client step 4': 'None',
      'Pos client step 1 action plan': 'None',
      'Pos client step 2 action plan': 'None',
      'Pos client step 3 action plan': 'None',
      'Pos client risk 1': 'None',
      'Pos client risk 2': 'None',
      'Pos client risk 3': 'None',
      'Pos client risk 1 stage': 'None',
      'Pos client risk 2 stage': 'None',
      'Pos client risk 3 stage': 'None',
      'Pos client risk 1 plan': 'None',
      'Pos client risk 2 plan': 'None',
      'Pos client risk 3 plan': 'None',
      'Referral': 'None',
      'Referral Point': 'None',
      'Why was the client referred': 'None',
      'End of window period': 'None',
      'Follow up required': 'None',
      'Reason for follow up': 'None',
      'Follow up date': 'None',
  },
  {
      name: 'Skylar',
      'Site name': 'Brakenfell',
      'Site type': 'Brakenfell High',
      'Sub district': 'Northern Suburbs',
      'Date': '10 January 2021',
      'Counsellor name': 'Anwar',
      'Time in': '15h00',
      'Gender': 'Female',
      'Birthdate': '6 September 1997',
      'Age at intake':'16',
      'Grade':'11',
      'Race':'Coloured',
      'Mobile': '0786093748',
      'Consent to sms': '0738293672',
      'Home phone number': '021 502 6464',
      'Client community': 'Brakenfell',
      'Client name and surname':'Skylar Williams',
      'First time doing an Hiv test':'Yes' ,
      'First time doing with Life Choices': 'Yes',
      'How many times tested': '10',
      'Last Hiv test': 'last year November',
      'Last test result': 'Negative',
      'TB screening result': 'None',
      'Scheduled follow up test': 'None',
      'Has client ever had sex': 'Yes',
      'Last had unprotected sex': '2019',
      'Blood contact': 'None',
      'STI screening result': 'None',
      'Time out': '16h00',
      'Last name': 'Williams',
      'Salesforce Client Code': '1234567',
      'Receive test results': 'Yes',
      'Reason for no test result': 'None',
      'Hiv test result': 'Negative',
      'Maintenance plan': 'None',
      'Negative client risk 1': 'None',
      'Negative client risk 2': 'None',
      'Negative client risk 3': 'None',
      'Negative client risk 1 stage': 'None',
      'Negative client risk 2 stage': 'None',
      'Negative client risk 3 stage': 'None',
      'Negative client risk 1 plan': 'None',
      'Negative client risk 2 plan': 'None',
      'Negative client risk 3 plan': 'None',
      'Pos client step 1': 'None',
      'Pos client step 2': 'None',
      'Pos client step 3': 'None',
      'Pos client step 4': 'None',
      'Pos client step 1 action plan': 'None',
      'Pos client step 2 action plan': 'None',
      'Pos client step 3 action plan': 'None',
      'Pos client risk 1': 'None',
      'Pos client risk 2': 'None',
      'Pos client risk 3': 'None',
      'Pos client risk 1 stage': 'None',
      'Pos client risk 2 stage': 'None',
      'Pos client risk 3 stage': 'None',
      'Pos client risk 1 plan': 'None',
      'Pos client risk 2 plan': 'None',
      'Pos client risk 3 plan': 'None',
      'Referral': 'None',
      'Referral Point': 'None',
      'Why was the client referred': 'None',
      'End of window period': 'None',
      'Follow up required': 'None',
      'Reason for follow up': 'None',
      'Follow up date': 'None',
  }
        ]
    }
  }
}
</script>

<style scoped>
.entry-container{
  margin: 20px;
  padding: 20px;
}
.download{
   box-shadow: 1px 4px 10px 3px rgba(0, 0, 0, 0.25);
   border-radius: 15px;
}
</style>